import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as THREE from 'three';
import './styles.css';

const missions=[
{id:'wallet',state:'Lagos',title:'Get Your First Wallet',lesson:'A wallet is your key to Web3. Your address is public; your recovery phrase is private.',steps:['Find the Web3 Hub','Talk to Ada','Open the wallet tutorial','Complete the safety check'],reward:100},
{id:'transaction',state:'Oyo',title:'Send It Onchain',lesson:'Transactions are signed actions recorded by a blockchain. Gas is the network fee for processing them.',steps:['Reach the community hub','Inspect the transaction','Choose the correct network','Confirm the lesson'],reward:150},
{id:'swap',state:'Rivers',title:'Swap Without Getting Swapped',lesson:'A DEX lets users trade tokens from their own wallets. Always verify the token, route and slippage.',steps:['Meet the trader','Read the quote','Spot the fake token','Finish the swap lesson'],reward:200},
{id:'security',state:'FCT Abuja',title:'Protect The Bag',lesson:'Never share a seed phrase or sign a transaction you do not understand. Fake support accounts are everywhere.',steps:['Find the security office','Inspect three messages','Reject the phishing attempt','Lock in the lesson'],reward:250}
];
const STATES=['Lagos','Oyo','Ogun','Osun','Ondo','Ekiti','Kwara','Kogi','Benue','Nasarawa','FCT Abuja','Kaduna','Kano','Katsina','Jigawa','Bauchi','Gombe','Yobe','Borno','Adamawa','Taraba','Plateau','Niger','Zamfara','Sokoto','Kebbi','Rivers','Bayelsa','Delta','Edo','Akwa Ibom','Cross River','Abia','Imo','Enugu','Anambra','Ebonyi'];

function Game({onExit}){
 const mount=useRef(null),keys=useRef({}),player=useRef({x:0,z:12,rot:0});
 const [started,setStarted]=useState(false),[paused,setPaused]=useState(false),[mission,setMission]=useState(0),[step,setStep]=useState(0),[xp,setXp]=useState(0),[toast,setToast]=useState('');
 const current=missions[mission];
 useEffect(()=>{
  const el=mount.current;if(!el)return;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x071013);scene.fog=new THREE.Fog(0x071013,28,115);
  const camera=new THREE.PerspectiveCamera(58,el.clientWidth/el.clientHeight,.1,220);camera.position.set(0,9,27);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(el.clientWidth,el.clientHeight);renderer.shadowMap.enabled=true;el.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xa8d8d0,0x15110c,2.1));const sun=new THREE.DirectionalLight(0xffe5b8,2.5);sun.position.set(-25,35,15);sun.castShadow=true;scene.add(sun);
  const world=new THREE.Group();scene.add(world);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x25312d,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
  const roadMat=new THREE.MeshStandardMaterial({color:0x111516,roughness:.92});
  for(let i=-3;i<=3;i++){const r=new THREE.Mesh(new THREE.PlaneGeometry(11,180),roadMat);r.rotation.x=-Math.PI/2;r.position.x=i*28;world.add(r);const l=new THREE.Mesh(new THREE.PlaneGeometry(.14,180),new THREE.MeshBasicMaterial({color:0xb7a77a}));l.rotation.x=-Math.PI/2;l.position.x=i*28;world.add(l);const h=new THREE.Mesh(new THREE.PlaneGeometry(180,11),roadMat);h.rotation.x=-Math.PI/2;h.position.z=i*28;world.add(h)}
  const palette=[0x9a6a4f,0xc38a58,0x7e8c85,0x6e554c,0x9b8b68,0x526d69];
  for(let gx=-3;gx<=3;gx++)for(let gz=-3;gz<=3;gz++){if((gx+gz)%3===0)continue;for(let k=0;k<2;k++){const w=5+Math.abs((gx*13+gz*5+k*7)%5),d=5+Math.abs((gz*11+gx*3+k*4)%5),h=4+Math.abs((gx*5+gz*9+k*6)%7);const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:palette[Math.abs(gx+gz+k)%palette.length],roughness:.86}));b.position.set(gx*28+(k?7:-7),h/2,gz*28+(k?7:-7));b.castShadow=true;b.receiveShadow=true;world.add(b)}}
  const marker=(x,z,color)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.1,.18,24),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.85}));m.position.set(x,.12,z);world.add(m);return m};const markers=[marker(-28,0,0x16e4d1),marker(28,28,0xffb24d),marker(0,-28,0x5bc0ff)];
  const avatar=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.15,4,8),new THREE.MeshStandardMaterial({color:0x16e4d1}));body.position.y=1.15;body.castShadow=true;avatar.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.45,16,12),new THREE.MeshStandardMaterial({color:0x6f412f}));head.position.y=2.05;head.castShadow=true;avatar.add(head);world.add(avatar);
  const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};window.addEventListener('resize',resize);
  const down=e=>{keys.current[e.key.toLowerCase()]=true;if(e.key==='e'||e.key===' ')window.dispatchEvent(new Event('kit-interact'))};const up=e=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener('keydown',down);window.addEventListener('keyup',up);
  const clock=new THREE.Clock();let raf;const loop=()=>{raf=requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04);if(started&&!paused){let dx=0,dz=0;if(keys.current.w||keys.current.arrowup)dz-=1;if(keys.current.s||keys.current.arrowdown)dz+=1;if(keys.current.a||keys.current.arrowleft)dx-=1;if(keys.current.d||keys.current.arrowright)dx+=1;const len=Math.hypot(dx,dz)||1,speed=keys.current.shift?10:6;player.current.x=THREE.MathUtils.clamp(player.current.x+dx/len*speed*dt,-82,82);player.current.z=THREE.MathUtils.clamp(player.current.z+dz/len*speed*dt,-82,82);if(dx||dz)player.current.rot=Math.atan2(dx,dz);avatar.position.set(player.current.x,0,player.current.z);avatar.rotation.y=player.current.rot;camera.position.lerp(new THREE.Vector3(player.current.x,9,player.current.z+15),.08);camera.lookAt(player.current.x,1,player.current.z);markers.forEach((m,i)=>{m.rotation.z+=dt*(i+1);m.scale.setScalar(1+.08*Math.sin(performance.now()/250+i))})}renderer.render(scene,camera)};loop();
  return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);renderer.dispose();if(el.contains(renderer.domElement))el.removeChild(renderer.domElement)};
 },[started,paused]);
 const interact=()=>{const target=[[-28,0],[28,28],[0,-28],[-28,0]][Math.min(mission,3)];if(Math.hypot(player.current.x-target[0],player.current.z-target[1])<9){if(step<current.steps.length-1){setStep(v=>v+1);setToast(current.steps[step+1])}else{setXp(v=>v+current.reward);setToast('Mission complete — next chapter unlocked.');setMission(v=>Math.min(v+1,missions.length-1));setStep(0)}}else setToast('Move closer to the glowing mission marker.');setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{window.addEventListener('kit-interact',interact);return()=>window.removeEventListener('kit-interact',interact)},[mission,step]);
 return <div className="game-shell"><div ref={mount} className="viewport"/><div className="hud"><div className="topbar"><div><b>KIT<span>NAIJA</span></b><small>WEB3 MISSION CITY</small></div><div className="xp">XP <strong>{xp}</strong></div><button onClick={()=>setPaused(v=>!v)}>{paused?'RESUME':'PAUSE'}</button></div><div className="mission"><div className="eyebrow">MISSION · {current.state}</div><h2>{current.title}</h2><p>{current.lesson}</p><div className="progress">{current.steps.map((s,i)=><div className={i<step?'done':i===step?'active':''} key={s}><i/>{s}</div>)}</div><button className="primary" onClick={interact}>{step===current.steps.length-1?'COMPLETE MISSION':'INTERACT'} <span>E / SPACE</span></button></div><div className="controls"><span>WASD</span> MOVE <span>SHIFT</span> RUN <span>E / SPACE</span> INTERACT</div>{toast&&<div className="toast">{toast}</div>}{paused&&<div className="pause"><h1>PAUSED</h1><p>Your mission stays exactly where you left it.</p><button className="primary" onClick={()=>setPaused(false)}>CONTINUE</button></div>}<button className="exit" onClick={onExit}>EXIT CITY</button></div>{!started&&<div className="start-overlay"><div><div className="eyebrow">LAGOS · CHAPTER 01</div><h1>WELCOME TO<br/><span>KITNAIJA.</span></h1><p>Walk into the city. Your first mission is waiting at the Web3 Hub.</p><button className="primary" onClick={()=>setStarted(true)}>START MISSION <span>ENTER</span></button></div></div>}</div>;
}
function App(){const [play,setPlay]=useState(false),[name,setName]=useState('');return play?<Game onExit={()=>setPlay(false)}/>:<main className="landing"><nav><div className="brand">KIT<span>NAIJA</span></div><div className="navtag">36 STATES · 1 ONCHAIN JOURNEY</div></nav><section className="hero"><div className="copy"><div className="kicker">THE NIGERIA WEB3 MISSION GAME</div><h1>LEARN<br/><em>ONCHAIN.</em><br/>IN THE CITY.</h1><p>Explore Nigeria, meet people, complete real missions and learn Web3 by doing — wallets, transactions, swaps, security and more.</p><div className="start"><input value={name} onChange={e=>setName(e.target.value)} placeholder="ENTER YOUR NAME" maxLength={18}/><button onClick={()=>setPlay(true)}>ENTER KITNAIJA <b>→</b></button></div><div className="micro"><span>●</span> NO WALLET REQUIRED TO START</div></div><div className="map-art"><div className="sun"/><div className="road r1"/><div className="road r2"/><div className="block b1"/><div className="block b2"/><div className="block b3"/><div className="pin">WEB3<br/>HUB</div><div className="citylabel">LAGOS<br/><small>MISSION 01</small></div></div></section><footer><span>36 STATES + FCT</span><span>MISSION-DRIVEN ONBOARDING</span><span>BUILT FOR NIGERIA</span></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);